//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Inputs/CameraInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Inputs/CameraInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CameraInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CameraInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""CameraInputs"",
    ""maps"": [
        {
            ""name"": ""CameraMovements"",
            ""id"": ""c0d6a4ae-cc73-46c9-a262-fd2852b433c9"",
            ""actions"": [
                {
                    ""name"": ""Movements"",
                    ""type"": ""Value"",
                    ""id"": ""3217a8e8-7412-4e89-bc33-fc0fac442dcb"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Speeding"",
                    ""type"": ""Button"",
                    ""id"": ""af5bf533-79bf-4f80-a5a1-98e6c72c8c11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""View"",
                    ""type"": ""Value"",
                    ""id"": ""3060637b-5d27-4fef-a515-1d9041f8c332"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""7119e3ca-096c-4b61-b883-5e88ab3bb7e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""6ec8ee95-7891-4afe-9c9d-c93f7326754d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""fbc667b7-d07b-44ae-a487-ff47b5a3de48"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4931dc01-d81c-47e9-8e73-335ebde55922"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ee8f6ea3-faf8-4e9c-8666-4c8d365acc62"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c891a415-b14e-4311-8f8a-281647c05e43"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""aaa10bcd-8952-4cf9-8674-e5cc1640f9aa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""2b0b47d0-f01e-48cd-a805-5405da6235e7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""e5a03611-e85d-4501-8d7e-dee4116b3d58"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movements"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d7646d0d-08cc-4c98-86ad-86901935c50d"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speeding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5190dc9-4a98-4ace-9bd9-1852ed2d9568"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1979900-e184-42b8-888d-b382c451a9e3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feba831b-c8ae-4f01-b782-60ec93fd1af9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMenuControls"",
            ""id"": ""6a3a1ab4-92ba-49fc-89aa-12ce4426985e"",
            ""actions"": [
                {
                    ""name"": ""OpenCloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""ab5d9d73-b9fe-4696-bc09-389302a1d9d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""85f22323-8c37-4894-870b-a31e5d39a1bc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConsoleOpen"",
                    ""type"": ""Button"",
                    ""id"": ""cbd5cdd0-cf24-4782-9b64-cb5efda65840"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4af93e44-2db1-4513-8b17-b7bc23752e93"",
                    ""path"": ""<Keyboard>/#(M)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9447277-5477-4520-8438-adac77ee4230"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7b5821b-cd91-4cdc-845e-b0cc190bd712"",
                    ""path"": ""<Keyboard>/quote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConsoleOpen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CameraMovements
        m_CameraMovements = asset.FindActionMap("CameraMovements", throwIfNotFound: true);
        m_CameraMovements_Movements = m_CameraMovements.FindAction("Movements", throwIfNotFound: true);
        m_CameraMovements_Speeding = m_CameraMovements.FindAction("Speeding", throwIfNotFound: true);
        m_CameraMovements_View = m_CameraMovements.FindAction("View", throwIfNotFound: true);
        m_CameraMovements_LeftClick = m_CameraMovements.FindAction("LeftClick", throwIfNotFound: true);
        m_CameraMovements_RightClick = m_CameraMovements.FindAction("RightClick", throwIfNotFound: true);
        // PlayerMenuControls
        m_PlayerMenuControls = asset.FindActionMap("PlayerMenuControls", throwIfNotFound: true);
        m_PlayerMenuControls_OpenCloseMenu = m_PlayerMenuControls.FindAction("OpenCloseMenu", throwIfNotFound: true);
        m_PlayerMenuControls_Debug = m_PlayerMenuControls.FindAction("Debug", throwIfNotFound: true);
        m_PlayerMenuControls_ConsoleOpen = m_PlayerMenuControls.FindAction("ConsoleOpen", throwIfNotFound: true);
    }

    ~@CameraInputs()
    {
        UnityEngine.Debug.Assert(!m_CameraMovements.enabled, "This will cause a leak and performance issues, CameraInputs.CameraMovements.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerMenuControls.enabled, "This will cause a leak and performance issues, CameraInputs.PlayerMenuControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraMovements
    private readonly InputActionMap m_CameraMovements;
    private List<ICameraMovementsActions> m_CameraMovementsActionsCallbackInterfaces = new List<ICameraMovementsActions>();
    private readonly InputAction m_CameraMovements_Movements;
    private readonly InputAction m_CameraMovements_Speeding;
    private readonly InputAction m_CameraMovements_View;
    private readonly InputAction m_CameraMovements_LeftClick;
    private readonly InputAction m_CameraMovements_RightClick;
    /// <summary>
    /// Provides access to input actions defined in input action map "CameraMovements".
    /// </summary>
    public struct CameraMovementsActions
    {
        private @CameraInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CameraMovementsActions(@CameraInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CameraMovements/Movements".
        /// </summary>
        public InputAction @Movements => m_Wrapper.m_CameraMovements_Movements;
        /// <summary>
        /// Provides access to the underlying input action "CameraMovements/Speeding".
        /// </summary>
        public InputAction @Speeding => m_Wrapper.m_CameraMovements_Speeding;
        /// <summary>
        /// Provides access to the underlying input action "CameraMovements/View".
        /// </summary>
        public InputAction @View => m_Wrapper.m_CameraMovements_View;
        /// <summary>
        /// Provides access to the underlying input action "CameraMovements/LeftClick".
        /// </summary>
        public InputAction @LeftClick => m_Wrapper.m_CameraMovements_LeftClick;
        /// <summary>
        /// Provides access to the underlying input action "CameraMovements/RightClick".
        /// </summary>
        public InputAction @RightClick => m_Wrapper.m_CameraMovements_RightClick;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CameraMovements; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CameraMovementsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CameraMovementsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CameraMovementsActions" />
        public void AddCallbacks(ICameraMovementsActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraMovementsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraMovementsActionsCallbackInterfaces.Add(instance);
            @Movements.started += instance.OnMovements;
            @Movements.performed += instance.OnMovements;
            @Movements.canceled += instance.OnMovements;
            @Speeding.started += instance.OnSpeeding;
            @Speeding.performed += instance.OnSpeeding;
            @Speeding.canceled += instance.OnSpeeding;
            @View.started += instance.OnView;
            @View.performed += instance.OnView;
            @View.canceled += instance.OnView;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CameraMovementsActions" />
        private void UnregisterCallbacks(ICameraMovementsActions instance)
        {
            @Movements.started -= instance.OnMovements;
            @Movements.performed -= instance.OnMovements;
            @Movements.canceled -= instance.OnMovements;
            @Speeding.started -= instance.OnSpeeding;
            @Speeding.performed -= instance.OnSpeeding;
            @Speeding.canceled -= instance.OnSpeeding;
            @View.started -= instance.OnView;
            @View.performed -= instance.OnView;
            @View.canceled -= instance.OnView;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CameraMovementsActions.UnregisterCallbacks(ICameraMovementsActions)" />.
        /// </summary>
        /// <seealso cref="CameraMovementsActions.UnregisterCallbacks(ICameraMovementsActions)" />
        public void RemoveCallbacks(ICameraMovementsActions instance)
        {
            if (m_Wrapper.m_CameraMovementsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CameraMovementsActions.AddCallbacks(ICameraMovementsActions)" />
        /// <seealso cref="CameraMovementsActions.RemoveCallbacks(ICameraMovementsActions)" />
        /// <seealso cref="CameraMovementsActions.UnregisterCallbacks(ICameraMovementsActions)" />
        public void SetCallbacks(ICameraMovementsActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraMovementsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraMovementsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CameraMovementsActions" /> instance referencing this action map.
    /// </summary>
    public CameraMovementsActions @CameraMovements => new CameraMovementsActions(this);

    // PlayerMenuControls
    private readonly InputActionMap m_PlayerMenuControls;
    private List<IPlayerMenuControlsActions> m_PlayerMenuControlsActionsCallbackInterfaces = new List<IPlayerMenuControlsActions>();
    private readonly InputAction m_PlayerMenuControls_OpenCloseMenu;
    private readonly InputAction m_PlayerMenuControls_Debug;
    private readonly InputAction m_PlayerMenuControls_ConsoleOpen;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerMenuControls".
    /// </summary>
    public struct PlayerMenuControlsActions
    {
        private @CameraInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerMenuControlsActions(@CameraInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerMenuControls/OpenCloseMenu".
        /// </summary>
        public InputAction @OpenCloseMenu => m_Wrapper.m_PlayerMenuControls_OpenCloseMenu;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMenuControls/Debug".
        /// </summary>
        public InputAction @Debug => m_Wrapper.m_PlayerMenuControls_Debug;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMenuControls/ConsoleOpen".
        /// </summary>
        public InputAction @ConsoleOpen => m_Wrapper.m_PlayerMenuControls_ConsoleOpen;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerMenuControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerMenuControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerMenuControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerMenuControlsActions" />
        public void AddCallbacks(IPlayerMenuControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMenuControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMenuControlsActionsCallbackInterfaces.Add(instance);
            @OpenCloseMenu.started += instance.OnOpenCloseMenu;
            @OpenCloseMenu.performed += instance.OnOpenCloseMenu;
            @OpenCloseMenu.canceled += instance.OnOpenCloseMenu;
            @Debug.started += instance.OnDebug;
            @Debug.performed += instance.OnDebug;
            @Debug.canceled += instance.OnDebug;
            @ConsoleOpen.started += instance.OnConsoleOpen;
            @ConsoleOpen.performed += instance.OnConsoleOpen;
            @ConsoleOpen.canceled += instance.OnConsoleOpen;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerMenuControlsActions" />
        private void UnregisterCallbacks(IPlayerMenuControlsActions instance)
        {
            @OpenCloseMenu.started -= instance.OnOpenCloseMenu;
            @OpenCloseMenu.performed -= instance.OnOpenCloseMenu;
            @OpenCloseMenu.canceled -= instance.OnOpenCloseMenu;
            @Debug.started -= instance.OnDebug;
            @Debug.performed -= instance.OnDebug;
            @Debug.canceled -= instance.OnDebug;
            @ConsoleOpen.started -= instance.OnConsoleOpen;
            @ConsoleOpen.performed -= instance.OnConsoleOpen;
            @ConsoleOpen.canceled -= instance.OnConsoleOpen;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerMenuControlsActions.UnregisterCallbacks(IPlayerMenuControlsActions)" />.
        /// </summary>
        /// <seealso cref="PlayerMenuControlsActions.UnregisterCallbacks(IPlayerMenuControlsActions)" />
        public void RemoveCallbacks(IPlayerMenuControlsActions instance)
        {
            if (m_Wrapper.m_PlayerMenuControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerMenuControlsActions.AddCallbacks(IPlayerMenuControlsActions)" />
        /// <seealso cref="PlayerMenuControlsActions.RemoveCallbacks(IPlayerMenuControlsActions)" />
        /// <seealso cref="PlayerMenuControlsActions.UnregisterCallbacks(IPlayerMenuControlsActions)" />
        public void SetCallbacks(IPlayerMenuControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMenuControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMenuControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerMenuControlsActions" /> instance referencing this action map.
    /// </summary>
    public PlayerMenuControlsActions @PlayerMenuControls => new PlayerMenuControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CameraMovements" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CameraMovementsActions.AddCallbacks(ICameraMovementsActions)" />
    /// <seealso cref="CameraMovementsActions.RemoveCallbacks(ICameraMovementsActions)" />
    public interface ICameraMovementsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Movements" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovements(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Speeding" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpeeding(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "View" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnView(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightClick(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerMenuControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerMenuControlsActions.AddCallbacks(IPlayerMenuControlsActions)" />
    /// <seealso cref="PlayerMenuControlsActions.RemoveCallbacks(IPlayerMenuControlsActions)" />
    public interface IPlayerMenuControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "OpenCloseMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenCloseMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Debug" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDebug(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ConsoleOpen" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConsoleOpen(InputAction.CallbackContext context);
    }
}
